### ISSUE TITLE
nhplus-11/accessibility of treatments

### ISSUE THREAD

**Issue by PicoLuetjens** [PicoLuetjens/NHPlus#17]
### User Story
Als Arzt möchte ich die am Patienten verübten Behandlungen und Medikamente angeben und einsehen, außerdem wäre es schön, wenn ich Medikamenten Behandlungen vorplanen kann, damit die Schwestern wissen, wann und was der Patient an Medizin bekommen soll, dies würde mir auch etwas Zeit sparen und mehr für mehr Patienten offenlassen. Dazu würde ich gerne auch eingetragene Behandlungen abändern können, aber nur ich sollte das machen können.

### Akzeptanzkriterien
- Behandlungen sollen einsehbar sein
- Behandlungen sollen vorgeplant werden können
- Nur Berechtigte dürfen Behandlungseinträge ändern können

### Tasks
- [ ] "Alle" - Selektor ei Behandlungen muss funktionieren
- [ ] User Accounts erstellen/mit Login
- [ ] Berechtigungen zum Bearbeiten von Einträgen vergeben und kontrollieren beim Versuch

### Testfälle
- Vorbedingung: Eine Behandlung wurde angelegt

- auszuführende Testschritte: Änderung des Eintrags versuchen von berechtigen Account und von unberechtigten.

- erwartetes Ergebnis: Berechtigter Account darf Eintrag ändern, während unberechtigter das nicht kann
