### ISSUE TITLE
nhplus-13/presets of treatments

### ISSUE THREAD

**Issue by PicoLuetjens** [PicoLuetjens/NHPlus#19]
### User Story
Als Pflegerin möchte ich meine begrenzte Zeit nicht für die lästigen Dokumentationen verbrauchen. Ich würde mir wünschen, dass ich bei Daily Things Vorlagen für die Dokumentation hätte, um die eingesparte Zeit für die Patienten zu nutzen. Dazu wäre es praktisch, wenn ich sehen könnte, wie viel Zeit ich für den jeweiligen Patienten habe. Da ich nicht so IT-Affin bin, würde ich es auch gut finden, wenn ich auf jeder Seite, auf der ich mich im Programm befinde, einen Hover Button (?) habe der mir ein kurzen Hilfe Text anzeigt.

### Akzeptanzkriterien
- Auf jeder Seite muss ein Hover Button sein, mit einer kurzen Beschreibung
- Bei der Dokumentation soll es die Möglichkeit geben einen vorgeschriebenen Text auswählen zu können und ihn manuell zu ändern
- der Behandlung soll die verfügbare Zeit angezeigt werden

### Tasks
- [ ] Auf jeder Seite soll ein Hover Button hinzugefügt werden
- [ ] Es müssen zu jeder Seite kurze Texte geschrieben werden, die beschreiben, was man auf der Seite machen kann
- [ ] Beim Hover des Buttons soll ein kurzer Text erscheinen, der erklärt, was man auf der Seite alles machen kann
- [ ] In der Dokumentation soll es ein Feld mit vorgefertigten Dokumentationstexten geben
- [ ] Die Dokumentationstexte sollen manuell geändert werden können
- [ ] Bei der Behandlungsseite soll es ein Timer geben, der anzeigt, wie langen man noch Zeit hat

##### T1
- Vorbedingung: Auf jeder Seite wurden Hover Buttons angelegt und mit kurzen Texten beschrieben

- Auszuführende Testschritte: Über den Hover Button Hovert

- Erwartetes Ergebnis: Beim Hover des Buttons wird ein Text erscheinen, der beschreibt was man auf der Seite alles machen kann 

##### T2
- Vorbedingung: In der Dokumentation soll es ein Feld geben, wo man vorgefertigte Dokumentationstete auswählen kann

-  Auszuführende Testschritte: In der Dokumentation auf das Feld klicken und ein vorgefertigter Text auswählen (z.B Blutdruck messen)

- Erwartetes Ergebnis: Ausgewählter Text (Blutdruck messen) wird in der Dokumentation angezeigt

##### T3
- Vorbedingung: In der Dokumentation soll es ein Feld geben, wo man vorgefertigte Dokumentationstete auswählen und diesen Text manuell ändern kann

- Auszuführende Testschritte: In der Dokumentation auf das Feld klicken und ein vorgefertigter Text auswählen (z.B Blut nehmen) und mit manuellen Daten (z.B xxxml Blut genommen) ändern

- Erwartetes Ergebnis: Ausgewählter Text (Blut nehmen) wir in der Dokumentation anzeiget und kann manuell geändert werden

##### T4
- Vorbedingung: Es muss ein Timer geben, der anzeigt, wie lange man Zeit hat

- Auszuführende Testschritte: Es soll im Behandlungsbereich angeguckt werden, wie lange man Zeit hat

- Erwartetes Ergebnis: Es wird angezeigt, wie lange man Zeit man hat
