### ISSUE TITLE
nhplus-15/database integration

### ISSUE THREAD

**Issue by PicoLuetjens** [PicoLuetjens/NHPlus#21]
### User Story
Als Eigentümer möchte ich eine mit deutschem Recht konforme Datenspeicherung in meiner Software haben, die genau aufschlüsselt, welche Behandlungen an welchem Patienten zu welchem Zeitpunkt durchgeführt wurden. Das Ganze soll nach Möglichkeit nicht nur Lokal, sondern in einer Art Cloud gespeichert werden, um den Zugriff bei Bedarf zu erleichtern.

### Akzeptanzkriterien
- Datenspeicherung in einer Datenbank nach DSGVO Regeln
- Cloudanbindung

### Tasks
- [ ] Jede Behandlung muss mit einem Patienten verknüpft sein sowie Pfleger und behandelnder Arzt
- [ ] Jeder Datensatz muss verschlüsselt in einer Datenbank gespeichert werden
- [ ] Die Datenbank muss mit einer Cloud synchronisiert werden

### Testfälle
- Vorbedingung: SQL-Connection muss etabliert sein

- Auszuführende Testschritte: Einen Eintrag in der Software erstellen und prüfen, ob er in der Datenbank übernommen wurde

- Erwartetes Ergebnis: Eingetragene Daten tauchen korrekt in der Datenbank auf

**Comment by PicoLuetjens** [comment]
Geschlossen
