### ISSUE TITLE
nhplus-2/lock data of old treatments

### ISSUE THREAD

**Issue by PicoLuetjens** [PicoLuetjens/NHPlus#9]
### Description
Nurses that are not active anymore need to have a mechanism to be locked if they have done their last treatment sooner than 10 years and if they wish so. This data needs to be documented by law. After 10 years the nurse can be removed but the treatment should still be accessible.

##### tasks
- [x] data can be locked, to not be shown in view(basically the data is ignored)
- [x] when the last treatment of a nurse reaches 10 years the nurse should be removed  automatically from the nurse database by the application
- [x] treatments that were operated by a removed nurse should still be accessible and the field that displays nurse information should say something like "unknown data"

##### depends on
#13 nhplus-7/add nurse information in treatment view
